### ISSUE TITLE
How to add Authentication and Authorization to the schema

### ISSUE THREAD

**Issue by et-ent** [lnaegele/PSwag#2]
Is there a way to add Authentication and Authorization to the schema.json file?  The api requires  API keys to access most of the endpoints.  Swagger supports adding this to the swagger.json file.  I was looking through the code I don't see a place where I could set something to support this.

**Comment by lnaegele** [comment]
Hi et-ent,
I have now integrated authentication in PSwag. Please have a look at the documentation on how to use API Keys for securing your endpoints. Both, logic for securing your endpoint AND extending OpenAPI specification is provided by the new functionality, so you can use it out of the box.
